# //////////////////////////////////////////////////////
#                     GENERAL INPUT 
# //////////////////////////////////////////////////////

# -----------------------
#         CASE 
# -----------------------

country : &country None
year : &year None
sector : &sector None

# -----------------------
#         BASE 
# -----------------------

gas: &gas co2
limit: &limit 500
capture_cost: &capture_cost None
emission_cost: &emission_cost None
network_type: &network_type None
capture_method: &capture_method None

# PATHS
out_csv_path_temp : "./output/temp/csv/"
out_fig_path_temp : "./output/temp/fig/"
out_csv_path_final : "./output/final/csv/"
out_fig_path_final : "./output/final/fig/"

in_sink_path : "./input/storages.csv"


# FILE NAMES
optimal_network : "network.csv"
source_raw : "source_raw.csv"
sink_raw : "sink_raw.csv"
nodes_map_out: "nodes_map_out.html"
matrix_out: "matrix_out.csv"
network_results: "network_results.csv"
network_map_out: "network_map_out.html"
path_registry: "path_registry.csv"
path_vars: "path_vars.csv"
dac_out: "dac.csv"
totals_out: "totals.csv"


# +++++++++++++++++++++++++++temp


# API
source_api_url : "https://api.climatetrace.org/v6/assets?"
osrm_api_url : "http://router.project-osrm.org/route/v1/driving/"
osrm_api_table_url : "http://router.project-osrm.org/table/v1/driving/"
batch_size : 250

# COLUMNS
sink_id_col: &sink_id_col "id"
sink_capacity_col: &sink_capacity_col "sum_mid"
sink_lat_col: &sink_lat_col "latitude"
sink_lon_col: &sink_lon_col "longitude"
sink_country_col: &sink_country_col "country"
sink_name_col: &sink_name_col "site_name"

source_id_col: &source_id_col "id"
source_emit_col: &source_emit_col "emission"
source_lat_col: &source_lat_col "lat"
source_lon_col: &source_lon_col "lon"
source_name_col: &source_name_col "name"

# TRANSPORT
transport_method: &transport_method None


transport_cost:
  pipe:
    less_180: 0.08
    range_180_500: 0.12
    range_500_750: 0.15
    range_750_1500: 0.18
    more_1500: 0.24
  truck_ship:
    less_180: 0.36
    range_180_500: 0.36
    range_500_750: 0.36
    range_750_1500: 0.36
    more_1500: 0.36


quantity_cost_segments:
  pipe:
    "(0, 50000)": 2.5
    "(50000, 100000)": 1.5
    "(100000, 250000)": 0.9
    "(250000, 500000)": 0.6
    "(500000, 1000000)": 0.5
    "(1000000, 2000000)": 0.3
    "(2000000, 999999999)": 0.2
    # "(0, 50000)": 40
    # "(50000, 100000)": 20
    # "(100000, 250000)": 10
    # "(250000, 500000)": 6
    # "(500000, 1000000)": 2
    # "(1000000, 2000000)": 0.25
    # "(2000000, 999999999)": 0.15
  truck_ship:
    "(0, 50000)": 0.3
    "(50000, 100000)": 0.3
    "(100000, 250000)": 0.3
    "(250000, 500000)": 0.3
    "(500000, 1000000)": 0.3
    "(1000000, 2000000)": 0.3
    "(2000000, 999999999)": 0.3

# Stocking cost
stock_cost: 15