# //////////////////////////////////////////////////////
#                     GENERAL INPUT 
# //////////////////////////////////////////////////////

# -----------------------
#         CASE 
# -----------------------

country : &country None
year : &year None
sector : &sector None




# -----------------------
#         BASE 
# -----------------------

gas: &gas co2
limit: &limit 500
capture_cost: &capture_cost None
emission_cost: &emission_cost None

# PATHS
out_csv_path : "./output/pipeline/csv/"
out_fig_path : "./output/pipeline/fig/"
in_sink_path : "./input/storages.csv"

# FILE NAMES
nodes_map : "nodes_map.html"
optimal_network : "network.csv"


# ELASTIC 
es_host : "https://foliastream-8pgicrxzbcwccdvx4rexji.streamlit.app"
es_auth : ("elastic", "Tc=*1+gVuCPZmquLT_IQ")


# API
source_api_url : "https://api.climatetrace.org/v6/assets?"
osrm_api_url : "http://router.project-osrm.org/route/v1/driving/"


# INDEX
sink_index : sink
source_index : source


# QUERY
query : 
  query:
    match_all: {}
  size: 1000


# COLUMNS
sink_id_col: &sink_id_col "id"
sink_capacity_col: &sink_capacity_col "sum_mid"
sink_lat_col: &sink_lat_col "latitude"
sink_lon_col: &sink_lon_col "longitude"
sink_country_col: &sink_country_col "country"

source_id_col: &source_id_col "id"
source_emit_col: &source_emit_col "emission"
source_lat_col: &source_lat_col "lat"
source_lon_col: &source_lon_col "lon"


# MAPPINGS
mappings_sink:
  mappings:
    properties: 
      *sink_id_col:
        type: "keyword"
      *sink_capacity_col:
        type: "float"
      *sink_lat_col:
        type: "float"
      *sink_lon_col:
        type: "float"

mappings_source:
  mappings:
    properties:
      *source_id_col:
        type: "keyword"
      *source_emit_col:
        type: "float"
      *source_lat_col:
        type: "float"
      *source_lon_col:
        type: "float"


# TRANSPORT
transport_method: &transport_method truck_ship

transport_cost:
  pipe:
    less_180: 0.01417
    range_180_500: 0.01196
    range_500_750: 0.01147
    range_750_1500: 0.01139
    more_1500: 0.01132