
# //////////////////////////////////////////////////////
#                     GENERAL INPUT 
# //////////////////////////////////////////////////////

# -----------------------
#         CASE 
# -----------------------

country : &country None
year : &year None
sector : &sector None
capture_cost : None
emission_cost :  None
cluster_bool: False


# -----------------------
#         BASE 
# -----------------------

gas : &gas co2
limit : &limit 500

# -----------------------
#         PATHS
# -----------------------

out_csv_path : "./output/pipeline/csv/"
out_fig_path : "./output/pipeline/fig/"
in_sink_path : "./input/storages.csv"


# -----------------------
#      OUTPUT FILES
# -----------------------

output_map : "output_map.html"
output_network_map : "output_network_map.html"
output_network : "output_network.csv"
output_results_calc : "output_results_calc.csv"

# -----------------------
#         API
# -----------------------

source_api_url : "https://api.climatetrace.org/v6/assets?"

# -----------------------
#   ELASTIC CREDENTIALS
# -----------------------

es_host : "http://localhost:9200"
es_auth : ("elastic","Tc=*1+gVuCPZmquLT_IQ")

# -----------------------
#        INDEX
# -----------------------

source_index : source
sink_index : sink
matrix_index : matrix_sink_source
network_results_index : network_results
clusters_centroids_index : centroids



# -----------------------
#        COLUMNS
# -----------------------

source_id_col: &source_id_col "id"
source_emit_col: &source_emit_col "emission"
source_lat_col: &source_lat_col "lat"
source_lon_col: &source_lon_col "lon"
source_cluster_col: &source_cluster_col "cluster_label"

sink_id_col: &sink_id_col "id"
sink_capacity_col: &sink_capacity_col "sum_mid"
sink_lat_col: &sink_lat_col "latitude"
sink_lon_col: &sink_lon_col "longitude"
sink_country_col: &sink_country_col "country"

centroid_id_col: &centroid_id_col "id"
centroid_lat_col: &centroid_lat_col "lat"
centroid_lon_col: &centroid_lon_col "lon"

# -----------------------
#        MAPPINGS
# -----------------------

mappings_source:
  mappings:
    properties:
      *source_id_col:
        type: "keyword"
      *source_emit_col:
        type: "float"
      *source_lat_col:
        type: "float"
      *source_lon_col:
        type: "float"

mappings_source_clust:
  mappings:
    properties:
      *source_id_col:
        type: "keyword"
      *source_emit_col:
        type: "float"
      *source_lat_col:
        type: "float"
      *source_lon_col:
        type: "float"
      *source_cluster_col:
        type: "float"

mappings_sink:
  mappings:
    properties: 
      *sink_id_col:
        type: "keyword"
      *sink_capacity_col:
        type: "float"
      *sink_lat_col:
        type: "float"
      *sink_lon_col:
        type: "float"

mappings_centroids:
  mappings:
    properties:
      *centroid_id_col:
        type: "keyword"
      *centroid_lat_col:
        type: "float"
      *centroid_lon_col:
        type: "float"


# -----------------------
#        QUERY ALL
# -----------------------

query :
  query:
    match_all: {}
  size: 1000

query_matrix :
  query:
    match_all: {}
  size: 1000